services:
  postgres:
    image: postgres:15-alpine
    container_name: user-api-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-api-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  user-api-network:
    driver: bridge
