spring:
  # DataSource configurado automáticamente por RailwayDataSourceConfig.java
  # En Railway usa DATABASE_URL automática, en local usa configuración fallback
  datasource:
    # Configuración fallback para desarrollo local
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/user_management?sslmode=${DB_SSL_MODE:disable}&ApplicationName=${DB_APP_NAME:user-management-api}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Para app pequeña - máximo 10 usuarios
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false  # false para Railway
    clean-disabled: true
    out-of-order: false

# Configuración de Actuator para Railway (Segura)
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: never  # Cambiado de 'always' a 'never'
      show-components: never
      probes:
        enabled: true
  server:
    port: 8080

jwt:
  secret: ${JWT_SECRET:A8k9L3mN7pQ2sT6vY1wZ5xC4bF8dG9hJ2kL7nM4}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:user-management-api}
  audience: ${JWT_AUDIENCE:user-management-api-audience}

server:
  port: ${SERVER-PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    com.sordi.userManagement: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${SHOW_SQL:false}
    org.hibernate.type: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
