spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}&ApplicationName=${DB_APP_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 2000
      idle-timeout: 300000
      max-lifetime: 900000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    table: flyway_schema_history
    sql-migration-suffixes: .sql
    encoding: UTF-8
    validate-on-migrate: true

jwt:
  secret: A8k9L3mN7pQ2sT6vY1wZ5xC4bF8dG9hJ2kL7nM4
  expiration: 3600000
  refresh-expiration: 86400000
  issuer: user-management-api
  audience: user-management-api-audience

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    connection-timeout: 20000
    max-connections: 200
    threads:
      max: 50
      min-spare: 10
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.sordi.userManagement: INFO  # Corregido: userManagement (con M mayúscula)
    org.springframework.boot: INFO  # Agregado para logs de arranque
    org.springframework.security: WARN
    org.flywaydb: INFO  # Agregado para logs de migraciones
    com.zaxxer.hikari: INFO  # Agregado para logs del pool de conexiones
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-management-api.log
    max-size: 10MB
    max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: ping
