spring:
  datasource:
    # Configuraci칩n que funciona tanto para desarrollo local como Railway
    # Local: jdbc:postgresql://localhost:5432/user_management?sslmode=disable&ApplicationName=user-management-api
    # Railway: postgresql://postgres:password@host:port/database (se agrega jdbc: autom치ticamente)
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/user_management?sslmode=disable&ApplicationName=user-management-api}
    driver-class-name: org.postgresql.Driver
    hikari:
      # Para app peque침a - m치ximo 10 usuarios
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    table: flyway_schema_history
    sql-migration-suffixes: .sql
    encoding: UTF-8
    validate-on-migrate: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:A8k9L3mN7pQ2sT6vY1wZ5xC4bF8dG9hJ2kL7nM4}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:user-management-api}
  audience: ${JWT_AUDIENCE:user-management-api-audience}

server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    com.sordi.userManagement: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${SHOW_SQL:false}
    org.hibernate.type: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
